<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cms" nsURI="http://cin.ufpe.br/cms" nsPrefix="cms">
  <eClassifiers xsi:type="ecore:EClass" name="Home">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="#//Menu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footers" upperBound="-1"
        eType="#//Footer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menu" eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footer" eType="#//Footer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//Header"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Content"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerContent" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Footer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="footerContent" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerContent" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MENU_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//Entry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MENU_TYPE">
    <eLiterals name="HORIZONTAL_TOP"/>
    <eLiterals name="HORIZONTAL_MIDDLE"/>
    <eLiterals name="HORIZONTAL_BOTTOM"/>
    <eLiterals name="VERTIAL_LEFT"/>
    <eLiterals name="VERTICAL_RIGHT"/>
    <eLiterals name="VERTICAL_CENTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Propety">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry" eSuperTypes="#//Propety">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentTable" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableRows" upperBound="-1"
        eType="#//TableRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentText" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Paragraphs" upperBound="-1"
        eType="#//IText" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentList" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentEnumeration" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowCols" upperBound="-1"
        eType="#//TableCol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//IText"/>
  <eClassifiers xsi:type="ecore:EClass" name="IText" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//IText"/>
</ecore:EPackage>
